const GET_USERS = "GET_USERS";
const USER_LOADED = "USER_LOADED";
const USER_LOADING = "USER_LOADING";
const FETCH_REFS = "FETCH_REFS";
const SEARCH_USERS = "SEARCH_USERS";
const STORE_FILTERS = "STORE_FILTERS";
const AUTH_ERROR = "AUTH_ERROR";
const REGISTER_FAIL = "REGISTER_FAIL";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const PATCH_REFS = "PATCH_REFS";
const ADD_USER = "ADD_USER";
const LOADING = "LOADING";
const TRANSLATE = "TRANSLATE";
const TRANSLATE_FAIL = "TRANSLATE_FAIL";
const UPDATE_USER_LANGUAGES = "UPDATE_USER_LANGUAGES";

export enum ActionTypes {
  USER_LOADED = "USER_LOADED",
  USER_LOADING = "USER_LOADING",
  UPDATE_USER_LANGUAGES = "UPDATE_USER_LANGUAGES",
}

interface LoadingAction {
  type: string;
  payload: any;
}

export type Action = LoadingAction;